# Generated by Django 2.2.1 on 2019-10-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='gitHub',
            field=models.URLField(default='https://github.com/carlosmertens'),
        ),
    ]
